### ISSUE TITLE
where is flare ? is it opensourced?

### ISSUE THREAD

**Issue by feitian124** [soulteary/docker-flare#4]

**Comment by soulteary** [comment]
This project repository only provides the docker image of flare binary, see the readme for usage.

In terms of open source, not currently. see https://github.com/soulteary/docker-flare/issues/1

**Comment by feitian124** [comment]
get it, thanks, hope see it soon

**Comment by soulteary** [comment]
You're welcome, I will try my best to release the code cleanly before v0.5.

The part of Go interacting with static resources is too ugly to write in order to solve the rendering performance problem.

At present, if you are concerned about privacy issues, you can use proxy software to try to capture packets. The software does not have any external network requests except for accessing the Tencent Weather API `https://wis.qq.com/weather/common`.

**Comment by soulteary** [comment]
I have updated a version, if you are interested, you can try it out.

https://github.com/soulteary/docker-flare/releases/tag/v0.2.5


There is an offline mode in the settings document. In this mode, **flare will not initiate any public network requests** and can be used with peace of mind.

https://github.com/soulteary/docker-flare/blob/main/docs/advanced-startup.md

If you are still concerned, you can choose to use the following scheme to prevent the container from using the public network.

https://github.com/francoisruty/fruty_docker-outbound-restriction

@feitian124
